# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inet-wifi-gui/src/ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.networkList = QtWidgets.QListWidget(self.centralwidget)
        self.networkList.setObjectName("networkList")
        self.verticalLayout.addWidget(self.networkList)
        self.ssidLayout = QtWidgets.QHBoxLayout()
        self.ssidLayout.setObjectName("ssidLayout")
        self.ssidInput = QtWidgets.QLineEdit(self.centralwidget)
        self.ssidInput.setObjectName("ssidInput")
        self.ssidLayout.addWidget(self.ssidInput)
        self.passwordInput = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.ssidLayout.addWidget(self.passwordInput)
        self.showPasswordButton = QtWidgets.QPushButton(self.centralwidget)
        self.showPasswordButton.setObjectName("showPasswordButton")
        self.ssidLayout.addWidget(self.showPasswordButton)
        self.verticalLayout.addLayout(self.ssidLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.refreshButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshButton.setObjectName("refreshButton")
        self.buttonLayout.addWidget(self.refreshButton)
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setObjectName("connectButton")
        self.buttonLayout.addWidget(self.connectButton)
        self.disconnectButton = QtWidgets.QPushButton(self.centralwidget)
        self.disconnectButton.setObjectName("disconnectButton")
        self.buttonLayout.addWidget(self.disconnectButton)
        self.verticalLayout.addLayout(self.buttonLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "i-net WiFi Manager"))
        self.label.setText(_translate("MainWindow", "Wi-Fi Networks"))
        self.ssidInput.setPlaceholderText(_translate("MainWindow", "SSID (select or enter)"))
        self.passwordInput.setPlaceholderText(_translate("MainWindow", "Password"))
        self.showPasswordButton.setText(_translate("MainWindow", "Show"))
        self.refreshButton.setText(_translate("MainWindow", "Refresh"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.disconnectButton.setText(_translate("MainWindow", "Disconnect"))
